name: artie-base-image
labels:
  - docker-image
  - base-image
dependencies: ""
artifacts:
  - name: docker-image-amd64
    type: docker-image
  - name: docker-image-arm64
    type: docker-image
  - name: docker-image
    type: docker-manifest
type: build
steps:
  - job: docker-build
    artifacts:
      - docker-image-amd64
    img-base-name: artie-base
    buildx: true
    platform: linux/amd64
    dockerfile-dpath: "${REPO_ROOT}/framework/libraries/base-image"
    dockerfile: Dockerfile
    build-context: "."
    dependency-files:
      - "${REPO_ROOT}/framework/libraries/artie-util"
      - "${REPO_ROOT}/framework/libraries/artie-i2c"
      - "${REPO_ROOT}/framework/libraries/artie-gpio"
      - "${REPO_ROOT}/framework/libraries/artie-service-client"
      - "${REPO_ROOT}/framework/libraries/artie-tooling"
  - job: docker-build
    artifacts:
      - docker-image-arm64
    img-base-name: artie-base
    buildx: true
    platform: linux/arm64
    dockerfile-dpath: "${REPO_ROOT}/framework/libraries/base-image"
    dockerfile: Dockerfile
    build-context: "."
    dependency-files:
      - "${REPO_ROOT}/framework/libraries/artie-util"
      - "${REPO_ROOT}/framework/libraries/artie-i2c"
      - "${REPO_ROOT}/framework/libraries/artie-gpio"
      - "${REPO_ROOT}/framework/libraries/artie-service-client"
      - "${REPO_ROOT}/framework/libraries/artie-tooling"
  - job: docker-manifest
    artifacts:
      - docker-image
    img-base-name: artie-base
    images:
      - dependency:
          name: docker-image-amd64
          producing-task: artie-base-image
      - dependency:
          name: docker-image-arm64
          producing-task: artie-base-image
