name: open-ocd-image
labels:
  - docker-image
  - base-image
dependencies: ""
artifacts:
  - name: docker-image
    type: docker-image
type: build
steps:
  - job: docker-build
    artifacts:
      - docker-image
    img-base-name: openocd-base
    buildx: true
    platform: linux/arm64
    dockerfile-dpath: "${REPO_ROOT}/framework/libraries/base-image"
    dockerfile: Dockerfile.openocd
    build-context: "."
