name: logging-integration-tests
labels:
  - docker-image
  - integration
dependencies:
  - driver-eyebrows: docker-image
  - driver-reset: docker-image
  - log-collector: docker-image
  - artie-cli: docker-image
  - artie-api-server: docker-image
type: test
steps:
  - job: docker-compose-test-suite
    compose-fname: compose.logging.yaml
    compose-docker-image-variables:
      - RESET_TEST_IMAGE:
          dependency:
            name: docker-image
            producing-task: driver-reset
      - EYEBROWS_TEST_IMAGE:
          dependency:
            name: docker-image
            producing-task: driver-eyebrows
      - LOG_COLLECTOR_TEST_IMAGE:
          dependency:
            name: docker-image
            producing-task: log-collector
      - ARTIE_API_SERVER_TEST_IMAGE:
          dependency:
            name: docker-image
            producing-task: artie-api-server
    cli-image:
      dependency:
        name: docker-image
        producing-task: artie-cli
    steps:
      - test-name: init-mcu
        cmd-to-run-in-cli: "artie-cli help"
        expected-outputs:
          - what: "Writing 0x0 to "
            where: logging-itest-log-collector
          - what: "Mocking MCU FW load."
            where: logging-itest-log-collector
      - test-name: fw-load
        cmd-to-run-in-cli: "artie-cli eyebrows fw load --integration-test --artie-profile /integration_test_profile.json"
        expected-outputs:
          - what: "Writing 0x0 to "
            where: logging-itest-log-collector
          - what: "Mocking MCU FW load."
            where: logging-itest-log-collector
