name: artie-controller-node
labels:
  - yocto
dependencies:
  - yocto-controller-module: yocto-image
cli-args:
  - name: --device
    required: true
    help: "Path to the device (e.g., /dev/sdX) to flash the Yocto image onto."
  - name: --yocto-image
    required: true
    choices:
      - artie-image-dev
      - artie-image-release
    help: "The Yocto image to flash onto the device."
artifacts: []
type: flash
steps:
  - job: flash-yocto-image
    yocto-image:
      dependency:
        name: yocto-image
        producing-task: yocto-controller-module
