name: fw-mouth
labels:
  - firmware
dependencies:
  - pico-base-image: docker-image
artifacts:
  - name: docker-image
    type: docker-image
  - name: fw-files
    type: fw-files
type: build
steps:
  - job: docker-build
    artifacts:
      - docker-image
    img-base-name: artie-mouth
    buildx: false
    dockerfile-dpath: "${REPO_ROOT}/artie-common/firmware/mouth/build"
    dockerfile: Dockerfile
    build-context: "../.."
    build-args:
      - ARTIE_BASE_IMG:
          dependency:
            name: docker-image
            producing-task: pico-base-image
  - job: file-transfer-from-container
    artifacts:
      - fw-files
    image:
      dependency:
        name: docker-image
        producing-task: fw-mouth
    fw-files-in-container:
      - /pico/src/build/mouth.elf
      - /pico/src/build/mouth.hex
      - /pico/src/build/mouth.bin
      - /pico/src/build/mouth.uf2
